import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";

import { categoryColor, T } from "@/components/theme";
import { EmptyState, IconButton, Screen, Sheet } from "@/components/ui";
import { useContent } from "@/contexts/ContentContext";
import { useQuestEngine } from "@/contexts/QuestEngineContext";
import { Quest } from "@/types/content";

function ManageQuest({ quest, selected, onPress }: { quest: Quest; selected: boolean; onPress: () => void }) {
  const color = categoryColor[quest.category]?.text ?? quest.color;
  return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={onPress} style={({ pressed }) => ({ flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 19, borderWidth: 2, borderColor: selected ? T.blue : T.border, backgroundColor: selected ? `${T.blue}10` : T.white, padding: 13, opacity: pressed ? 0.72 : 1 })}><View style={{ width: 6, alignSelf: "stretch", borderRadius: 99, backgroundColor: color }} /><View style={{ flex: 1, minWidth: 0 }}><Text numberOfLines={1} style={{ color: T.dark, fontFamily: "RubikBold", fontSize: 15 }}>{quest.title}</Text><Text style={{ color, fontFamily: "RubikBold", fontSize: 10, marginTop: 3 }}>{quest.category} · {quest.timeLabel}</Text></View><Ionicons name={selected ? "checkmark-circle" : "square-outline"} size={24} color={selected ? T.blue : T.muted} /></Pressable>;
}

export function ManageSavedQuestsScreen({ onBack }: { onBack: () => void }) {
  const router = useRouter();
  const { quests, toggleSave } = useContent();
  const { userPacks, saveUserPack } = useQuestEngine();
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [collectionPickerOpen, setCollectionPickerOpen] = useState(false);
  const [selectedPackIds, setSelectedPackIds] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const filedIds = useMemo(() => new Set(userPacks.flatMap((pack) => pack.questIds)), [userPacks]);
  const available = useMemo(() => quests.filter((quest) => quest.saved && !filedIds.has(quest.id)), [filedIds, quests]);
  const selected = new Set(selectedIds);
  const toggle = (id: string) => setSelectedIds((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]);
  const unsave = async () => { if (!selectedIds.length || saving) return; setSaving(true); try { for (const id of selectedIds) await toggleSave(id); setSelectedIds([]); } finally { setSaving(false); } };
  const addToCollections = async () => { if (!selectedIds.length || !selectedPackIds.length || saving) return; setSaving(true); try { await Promise.all(userPacks.filter((pack) => selectedPackIds.includes(pack.id)).map((pack) => saveUserPack({ id: pack.id, title: pack.title, description: pack.description, icon: pack.icon, accentColor: pack.accentColor, coverImageUrl: pack.coverImageUrl, isPinned: pack.isPinned, questIds: [...new Set([...pack.questIds, ...selectedIds])] }))); setCollectionPickerOpen(false); setSelectedIds([]); setSelectedPackIds([]); } finally { setSaving(false); } };

  return <Screen scroll={false} padded={false}>
    <View style={{ flex: 1, paddingHorizontal: 20, paddingTop: 4, gap: 16 }}><View style={{ minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><IconButton icon="close" onPress={onBack} /><Text style={{ color: T.dark, fontFamily: "RubikBlack", fontSize: 20 }}>{selectedIds.length ? `${selectedIds.length} Selected` : "Manage Saved"}</Text><Pressable onPress={() => setSelectedIds(selectedIds.length === available.length ? [] : available.map((quest) => quest.id))}><Text style={{ color: T.blue, fontFamily: "RubikBold", fontSize: 13 }}>{selectedIds.length === available.length ? "Clear" : "Select all"}</Text></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ gap: 10, paddingBottom: 18 }}>{available.length ? available.map((quest) => <ManageQuest key={quest.id} quest={quest} selected={selected.has(quest.id)} onPress={() => toggle(quest.id)} />) : <EmptyState emoji="✅" title="Everything is organized" body="Unfiled saved quests will appear here when you save them." />}</ScrollView></View>
    <View style={{ paddingHorizontal: 20, paddingTop: 12, paddingBottom: 20, borderTopWidth: 1, borderTopColor: T.border, backgroundColor: T.bg, flexDirection: "row", gap: 10 }}><Pressable disabled={!selectedIds.length || saving} onPress={unsave} style={({ pressed }) => ({ flex: 1, minHeight: 54, borderRadius: 19, borderWidth: 2, borderColor: selectedIds.length ? T.border : T.border, backgroundColor: T.white, alignItems: "center", justifyContent: "center", opacity: selectedIds.length ? (pressed ? 0.75 : 1) : 0.5 })}><Text style={{ color: T.red, fontFamily: "RubikBold", fontSize: 14 }}>{saving ? "Working…" : "Unsave"}</Text></Pressable><Pressable disabled={!selectedIds.length || saving} onPress={() => setCollectionPickerOpen(true)} style={({ pressed }) => ({ flex: 1.35, minHeight: 54, borderRadius: 19, backgroundColor: T.blue, borderBottomWidth: 5, borderBottomColor: "#258fd8", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7, opacity: selectedIds.length ? (pressed ? 0.86 : 1) : 0.48, transform: [{ translateY: pressed ? 2 : 0 }] })}><Ionicons name="add" size={18} color={T.white} /><Text style={{ color: T.white, fontFamily: "RubikBold", fontSize: 14 }}>Add to collection</Text></Pressable></View>
    <Sheet visible={collectionPickerOpen} onClose={() => setCollectionPickerOpen(false)} maxHeight="74%"><View style={{ paddingHorizontal: 24, paddingBottom: 26, gap: 14 }}><View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><Text style={{ color: T.dark, fontFamily: "RubikBlack", fontSize: 20 }}>Add to collection</Text><Pressable onPress={addToCollections} disabled={!selectedPackIds.length || saving}><Text style={{ color: selectedPackIds.length ? T.blue : T.border, fontFamily: "RubikBold", fontSize: 15 }}>{saving ? "Saving…" : "Save"}</Text></Pressable></View><Text style={{ color: T.muted, fontFamily: "Rubik", fontSize: 13 }}>Choose one or more collections for these {selectedIds.length} quests.</Text>{userPacks.length ? <View style={{ gap: 6 }}>{userPacks.map((pack) => { const included = selectedPackIds.includes(pack.id); return <Pressable key={pack.id} onPress={() => setSelectedPackIds((ids) => included ? ids.filter((id) => id !== pack.id) : [...ids, pack.id])} style={{ minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12 }}><View style={{ width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: `${pack.accentColor}18` }}><Ionicons name="bookmarks" size={19} color={pack.accentColor} /></View><View style={{ flex: 1 }}><Text style={{ color: T.dark, fontFamily: "RubikBold", fontSize: 15 }}>{pack.title}</Text><Text style={{ color: T.muted, fontFamily: "Rubik", fontSize: 12 }}>{pack.questIds.length} quests</Text></View><Ionicons name={included ? "checkmark-circle" : "add-circle-outline"} size={24} color={included ? T.blue : T.muted} /></Pressable>; })}</View> : <EmptyState emoji="🗂️" title="Create a collection first" body="Then come back to organize these quests." action={<Pressable onPress={() => { setCollectionPickerOpen(false); router.push("/quest-collections"); }}><Text style={{ color: T.blue, fontFamily: "RubikBold" }}>Go to Collections</Text></Pressable>} />}</View></Sheet>
  </Screen>;
}
